-- Generated by tool/gen_seed.dart from lib/data/seed.dart. Do not edit by hand.
-- Demo creators without accounts, with their exercises, workouts and programs.

insert into public.creators (id, name, handle, tagline, bio, followers, price_monthly) values
  ('c_marko', 'Marko Petrović', 'marko.lifts', 'Snaga i hipertrofija', 'Trener snage iz Novog Sada. Radim sa šipkom, jednostavno i dosledno. Svaki trening ima jedan glavni pokret.', 48200, 5.99),
  ('c_jelena', 'Jelena Ilić', 'jelena.moves', 'Treninzi kod kuće', 'Bučice, trake i 40 minuta. Programi za one koji treniraju u dnevnoj sobi i žele da vide napredak.', 126000, 4.99),
  ('c_nikola', 'Nikola Jovanović', 'nikola.fit', 'Kalistenika', 'Vratilo, pod i sopstvena težina. Od prvog zgiba do deset u seriji.', 9400, 3.99)
on conflict (id) do update set name = excluded.name, handle = excluded.handle, tagline = excluded.tagline, bio = excluded.bio, followers = excluded.followers, price_monthly = excluded.price_monthly;

insert into public.exercises (id, creator_id, name, muscle, equipment, note, audience) values
  ('m_bench', 'c_marko', 'Bench press', 'chest', '{"barbell","bench"}', 'Lopatice skupljene, laktovi na 45°. Šipka dodiruje grudi, bez odbijanja.', 'public'),
  ('m_incline_db', 'c_marko', 'Kosi potisak bučicama', 'chest', '{"dumbbell","bench"}', 'Klupa na 30°. Spuštaj sporo, dve sekunde.', 'public'),
  ('m_ohp', 'c_marko', 'Rameni potisak', 'shoulders', '{"barbell"}', 'Stegni gluteus. Glava prolazi kroz ruke na vrhu.', 'public'),
  ('m_lateral', 'c_marko', 'Odručenje', 'shoulders', '{"dumbbell"}', 'Lakša težina, laktovi vode pokret.', 'public'),
  ('m_dips', 'c_marko', 'Propadanja', 'triceps', '{"bodyweight"}', 'Rame ne ide ispod lakta.', 'public'),
  ('m_pushdown', 'c_marko', 'Triceps sajla', 'triceps', '{"cable"}', 'Laktovi uz telo, pun opseg.', 'public'),
  ('m_deadlift', 'c_marko', 'Mrtvo dizanje', 'hamstrings', '{"barbell"}', 'Šipka uz noge. Gurni pod, ne vuci leđima.', 'public'),
  ('m_pullup', 'c_marko', 'Zgibovi', 'back', '{"pullupBar"}', 'Brada preko šipke, pun visi dole.', 'public'),
  ('m_row', 'c_marko', 'Veslanje šipkom', 'back', '{"barbell"}', 'Trup na 45°, šipka ka pupku.', 'public'),
  ('m_lat', 'c_marko', 'Lat povlačenje', 'back', '{"cable"}', 'Grudi ka šipki, bez ljuljanja.', 'public'),
  ('m_curl', 'c_marko', 'Biceps pregib', 'biceps', '{"dumbbell"}', 'Bez zamaha. Spusti do kraja.', 'public'),
  ('m_squat', 'c_marko', 'Čučanj', 'quads', '{"barbell"}', 'Kolena prate prste. Dubina ispod paralele ako kukovi dozvole.', 'public'),
  ('m_rdl', 'c_marko', 'Rumunsko mrtvo dizanje', 'hamstrings', '{"barbell"}', 'Kukovi nazad, kolena blago savijena.', 'public'),
  ('m_lunge', 'c_marko', 'Iskorak', 'quads', '{"dumbbell"}', 'Korak dovoljno dug da koleno ostane iznad stopala.', 'public'),
  ('m_legpress', 'c_marko', 'Nožna presa', 'quads', '{"machine"}', 'Donji deo leđa ostaje na naslonu.', 'public'),
  ('m_calf', 'c_marko', 'Podizanje na prste', 'calves', '{"machine"}', 'Pauza od sekunde gore i dole.', 'public'),
  ('m_hanging_leg', 'c_marko', 'Podizanje nogu u visu', 'core', '{"pullupBar"}', 'Bez ljuljanja, karlica se uvija.', 'public'),
  ('j_goblet', 'c_jelena', 'Gobl čučanj', 'quads', '{"dumbbell"}', 'Bučica uz grudi, laktovi između kolena.', 'public'),
  ('j_hip_thrust', 'c_jelena', 'Hip thrust sa trakom', 'glutes', '{"band"}', 'Brada ka grudima, stegni na vrhu dve sekunde.', 'public'),
  ('j_rdl_db', 'c_jelena', 'Rumunsko mrtvo bučicama', 'hamstrings', '{"dumbbell"}', 'Bučice klize uz butine.', 'public'),
  ('j_pushup', 'c_jelena', 'Sklekovi', 'chest', '{"bodyweight"}', 'Telo kao daska. Na kolenima je sasvim u redu.', 'public'),
  ('j_row_db', 'c_jelena', 'Veslanje bučicom', 'back', '{"dumbbell"}', 'Lakat ka džepu, ne ka plafonu.', 'public'),
  ('j_press_db', 'c_jelena', 'Rameni potisak bučicama', 'shoulders', '{"dumbbell"}', 'Sedi ili stoj, rebra dole.', 'public'),
  ('j_split_squat', 'c_jelena', 'Bugarski čučanj', 'quads', '{"dumbbell"}', 'Zadnja noga na kauču ili stolici.', 'public'),
  ('j_bridge', 'c_jelena', 'Glute bridge', 'glutes', '{"bodyweight"}', 'Pete blizu, guraj kroz pete.', 'public'),
  ('j_deadbug', 'c_jelena', 'Mrtva buba', 'core', '{"bodyweight"}', 'Donji deo leđa zalepljen za pod.', 'public'),
  ('j_band_abduction', 'c_jelena', 'Odmicanje sa trakom', 'glutes', '{"band"}', 'Traka iznad kolena, kontrola na povratku.', 'subscribers'),
  ('j_band_pull', 'c_jelena', 'Razvlačenje trake', 'back', '{"band"}', 'Ruke opružene, lopatice zajedno.', 'public'),
  ('n_pullup', 'c_nikola', 'Zgibovi', 'back', '{"pullupBar"}', 'Ako ne ide, skoči gore i spuštaj se pet sekundi.', 'public'),
  ('n_pushup', 'c_nikola', 'Sklekovi', 'chest', '{"bodyweight"}', 'Šake ispod ramena, grudi do poda.', 'public'),
  ('n_bench_dips', 'c_nikola', 'Propadanja na stolici', 'triceps', '{"bodyweight"}', 'Ramena dole, laktovi nazad.', 'public'),
  ('n_squat', 'c_nikola', 'Čučanj bez opreme', 'quads', '{"bodyweight"}', 'Sporo dole, eksplozivno gore.', 'public'),
  ('n_pistol', 'c_nikola', 'Pistol čučanj', 'quads', '{"bodyweight"}', 'Drži se za dovratak dok ne stekneš balans.', 'subscribers'),
  ('n_leg_raise', 'c_nikola', 'Podizanje nogu u visu', 'core', '{"pullupBar"}', 'Kolena ka grudima pa opruži kad bude lako.', 'public'),
  ('n_pike', 'c_nikola', 'Pike sklekovi', 'shoulders', '{"bodyweight"}', 'Kukovi visoko, glava ide ispred šaka.', 'public'),
  ('n_chinup', 'c_nikola', 'Zgibovi podhvatom', 'biceps', '{"pullupBar"}', 'Dlanovi ka tebi, laktovi uz telo.', 'public')
on conflict (id) do update set creator_id = excluded.creator_id, name = excluded.name, muscle = excluded.muscle, equipment = excluded.equipment, note = excluded.note, audience = excluded.audience;

insert into public.workouts (id, creator_id, name, exercises, finish_message, audience) values
  ('w_m_push', 'c_marko', 'Push day', '[{"exerciseId":"m_bench","sets":4,"repsMin":6,"repsMax":8,"rir":2,"restSeconds":150},{"exerciseId":"m_ohp","sets":3,"repsMin":8,"repsMax":10,"rir":2,"restSeconds":120},{"exerciseId":"m_incline_db","sets":3,"repsMin":10,"repsMax":12,"rir":1,"restSeconds":90},{"exerciseId":"m_lateral","sets":3,"repsMin":12,"repsMax":15,"rir":1,"restSeconds":60},{"exerciseId":"m_pushdown","sets":3,"repsMin":12,"repsMax":12,"rir":1,"restSeconds":60}]'::jsonb, 'Dobar potisak. Sledeće je Pull. Isti ritam.', 'public'),
  ('w_m_pull', 'c_marko', 'Pull day', '[{"exerciseId":"m_deadlift","sets":3,"repsMin":5,"repsMax":5,"rir":2,"restSeconds":180},{"exerciseId":"m_pullup","sets":4,"repsMin":6,"repsMax":10,"rir":1,"restSeconds":120},{"exerciseId":"m_row","sets":3,"repsMin":8,"repsMax":10,"rir":2,"restSeconds":90},{"exerciseId":"m_curl","sets":3,"repsMin":10,"repsMax":12,"rir":1,"restSeconds":60}]'::jsonb, 'Leđa su gotova. Sledeće su noge, odmori se.', 'public'),
  ('w_m_legs', 'c_marko', 'Noge', '[{"exerciseId":"m_squat","sets":4,"repsMin":5,"repsMax":6,"rir":2,"restSeconds":180},{"exerciseId":"m_rdl","sets":3,"repsMin":8,"repsMax":10,"rir":2,"restSeconds":120},{"exerciseId":"m_legpress","sets":3,"repsMin":10,"repsMax":12,"rir":1,"restSeconds":90},{"exerciseId":"m_calf","sets":4,"repsMin":12,"repsMax":15,"rir":1,"restSeconds":60}]'::jsonb, 'Najteži dan je iza tebe. Sutra hodaj polako.', 'public'),
  ('w_m_upper', 'c_marko', 'Gornji deo', '[{"exerciseId":"m_incline_db","sets":4,"repsMin":8,"repsMax":10,"rir":2,"restSeconds":90},{"exerciseId":"m_lat","sets":4,"repsMin":10,"repsMax":12,"rir":1,"restSeconds":90},{"exerciseId":"m_dips","sets":3,"repsMin":8,"repsMax":12,"rir":1,"restSeconds":90},{"exerciseId":"m_lateral","sets":3,"repsMin":15,"repsMax":15,"rir":0,"restSeconds":60},{"exerciseId":"m_hanging_leg","sets":3,"repsMin":10,"repsMax":12,"rir":null,"restSeconds":60}]'::jsonb, 'Nedelja je zatvorena. Sledeća počinje od Push day.', 'subscribers'),
  ('w_m_full_a', 'c_marko', 'Celo telo A', '[{"exerciseId":"m_squat","sets":3,"repsMin":8,"repsMax":8,"rir":3,"restSeconds":120},{"exerciseId":"m_bench","sets":3,"repsMin":8,"repsMax":8,"rir":3,"restSeconds":120},{"exerciseId":"m_row","sets":3,"repsMin":10,"repsMax":10,"rir":2,"restSeconds":90}]'::jsonb, 'Prvi korak je najvažniji. Sledeće je Celo telo B.', 'public'),
  ('w_m_full_b', 'c_marko', 'Celo telo B', '[{"exerciseId":"m_deadlift","sets":3,"repsMin":5,"repsMax":5,"rir":3,"restSeconds":150},{"exerciseId":"m_ohp","sets":3,"repsMin":8,"repsMax":8,"rir":2,"restSeconds":120},{"exerciseId":"m_lat","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":90}]'::jsonb, 'Još jedan. Sledeći put dodaj 2,5 kg na čučanj.', 'public'),
  ('w_j_lower', 'c_jelena', 'Donji deo', '[{"exerciseId":"j_goblet","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":75},{"exerciseId":"j_rdl_db","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":75},{"exerciseId":"j_hip_thrust","sets":3,"repsMin":15,"repsMax":15,"rir":1,"restSeconds":60},{"exerciseId":"j_deadbug","sets":3,"repsMin":10,"repsMax":10,"rir":null,"restSeconds":45}]'::jsonb, 'Noge gore, voda pored. Vidimo se za dva dana.', 'public'),
  ('w_j_upper', 'c_jelena', 'Gornji deo', '[{"exerciseId":"j_pushup","sets":3,"repsMin":8,"repsMax":12,"rir":1,"restSeconds":60},{"exerciseId":"j_row_db","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":60},{"exerciseId":"j_press_db","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":60},{"exerciseId":"j_band_pull","sets":3,"repsMin":15,"repsMax":15,"rir":null,"restSeconds":45}]'::jsonb, 'Ramena i leđa rade. Sledeće je celo telo.', 'public'),
  ('w_j_full', 'c_jelena', 'Celo telo', '[{"exerciseId":"j_split_squat","sets":3,"repsMin":8,"repsMax":10,"rir":2,"restSeconds":75},{"exerciseId":"j_pushup","sets":3,"repsMin":8,"repsMax":12,"rir":1,"restSeconds":60},{"exerciseId":"j_bridge","sets":3,"repsMin":15,"repsMax":20,"rir":null,"restSeconds":45},{"exerciseId":"j_row_db","sets":3,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":60}]'::jsonb, 'Tri treninga ove nedelje. To je ritam koji ostaje.', 'public'),
  ('w_j_glute_a', 'c_jelena', 'Gluteus A', '[{"exerciseId":"j_hip_thrust","sets":4,"repsMin":12,"repsMax":15,"rir":1,"restSeconds":60},{"exerciseId":"j_split_squat","sets":3,"repsMin":10,"repsMax":10,"rir":2,"restSeconds":75},{"exerciseId":"j_band_abduction","sets":3,"repsMin":20,"repsMax":20,"rir":null,"restSeconds":45}]'::jsonb, 'Stegni i pusti. Sledeći je Gluteus B.', 'subscribers'),
  ('w_j_glute_b', 'c_jelena', 'Gluteus B', '[{"exerciseId":"j_rdl_db","sets":4,"repsMin":10,"repsMax":12,"rir":2,"restSeconds":75},{"exerciseId":"j_bridge","sets":3,"repsMin":20,"repsMax":20,"rir":null,"restSeconds":45},{"exerciseId":"j_goblet","sets":3,"repsMin":12,"repsMax":12,"rir":2,"restSeconds":60}]'::jsonb, 'Gotovo za danas. Sledeće je Gluteus A.', 'subscribers'),
  ('w_n_pull', 'c_nikola', 'Vratilo', '[{"exerciseId":"n_pullup","sets":5,"repsMin":3,"repsMax":6,"rir":1,"restSeconds":120},{"exerciseId":"n_chinup","sets":3,"repsMin":5,"repsMax":8,"rir":1,"restSeconds":90},{"exerciseId":"n_leg_raise","sets":3,"repsMin":8,"repsMax":12,"rir":null,"restSeconds":60}]'::jsonb, 'Svaki zgib se računa. Sledeći put jedan više.', 'public'),
  ('w_n_push', 'c_nikola', 'Pod', '[{"exerciseId":"n_pushup","sets":4,"repsMin":10,"repsMax":20,"rir":1,"restSeconds":75},{"exerciseId":"n_pike","sets":3,"repsMin":6,"repsMax":10,"rir":2,"restSeconds":75},{"exerciseId":"n_bench_dips","sets":3,"repsMin":10,"repsMax":15,"rir":1,"restSeconds":60},{"exerciseId":"n_squat","sets":3,"repsMin":20,"repsMax":20,"rir":null,"restSeconds":60}]'::jsonb, 'Dobar posao. Vratilo te čeka sledeće.', 'public')
on conflict (id) do update set creator_id = excluded.creator_id, name = excluded.name, exercises = excluded.exercises, finish_message = excluded.finish_message, audience = excluded.audience;

insert into public.programs (id, creator_id, name, description, workout_ids, weeks, days_per_week, level, goal, place, audience) values
  ('p_m_strength', 'c_marko', 'Snaga 8', 'Četiri treninga nedeljno: push, pull, noge i gornji deo. Glavni pokreti rastu svake nedelje.', '{"w_m_push","w_m_pull","w_m_legs","w_m_upper"}', 8, 4, 'intermediate', 'strength', 'gym', 'subscribers'),
  ('p_m_start', 'c_marko', 'Početak', 'Dva treninga celog tela koja se smenjuju. Za prvih šest nedelja u teretani.', '{"w_m_full_a","w_m_full_b"}', 6, 3, 'beginner', 'strength', 'gym', 'public'),
  ('p_j_home', 'c_jelena', 'Kuća 30', 'Tri treninga od 30 do 40 minuta. Treba ti par bučica i traka.', '{"w_j_lower","w_j_upper","w_j_full"}', 6, 3, 'beginner', 'general', 'home', 'public'),
  ('p_j_glute', 'c_jelena', 'Gluteus plan', 'Četiri kraća treninga nedeljno sa fokusom na gluteus i zadnju ložu.', '{"w_j_glute_a","w_j_glute_b"}', 8, 4, 'intermediate', 'muscle', 'home', 'subscribers'),
  ('p_n_bar', 'c_nikola', 'Vratilo i pod', 'Kalistenika tri puta nedeljno. Cilj je deset zgibova u seriji.', '{"w_n_pull","w_n_push"}', 4, 3, 'beginner', 'strength', 'home', 'public')
on conflict (id) do update set creator_id = excluded.creator_id, name = excluded.name, description = excluded.description, workout_ids = excluded.workout_ids, weeks = excluded.weeks, days_per_week = excluded.days_per_week, level = excluded.level, goal = excluded.goal, place = excluded.place, audience = excluded.audience;

