/// Builds supabase/seed.sql from [SeedCatalog] (see tool/gen_seed.dart).
library;

import 'dart:convert';

import 'rows.dart';
import 'seed.dart';

String _literal(Object? v) => switch (v) {
  null => 'null',
  bool b => '$b',
  num n => '$n',
  String s => "'${s.replaceAll("'", "''")}'",
  List<String> l => "'{${l.map((x) => '"${x.replaceAll('"', r'\"')}"').join(',')}}'",
  _ => "'${jsonEncode(v).replaceAll("'", "''")}'::jsonb",
};

String _insert(String table, List<Row> rows) {
  if (rows.isEmpty) return '';
  final columns = rows.first.keys.toList();
  final values = rows.map((r) => '  (${columns.map((c) => _literal(r[c])).join(', ')})').join(',\n');
  final updates = columns.where((c) => c != 'id').map((c) => '$c = excluded.$c').join(', ');
  return 'insert into public.$table (${columns.join(', ')}) values\n$values\n'
      'on conflict (id) do update set $updates;\n\n';
}

String buildSeedSql() {
  final sql = StringBuffer()
    ..writeln('-- Generated by tool/gen_seed.dart from lib/data/seed.dart. Do not edit by hand.')
    ..writeln('-- Demo creators without accounts, with their exercises, workouts and programs.')
    ..writeln()
    ..write(_insert('creators', [for (final c in SeedCatalog.creators) creatorRow(c)]))
    ..write(_insert('exercises', [for (final e in SeedCatalog.exercises) exerciseRow(e)]))
    ..write(_insert('workouts', [for (final w in SeedCatalog.workouts) workoutRow(w)]))
    ..write(_insert('programs', [for (final p in SeedCatalog.programs) programRow(p)]));
  return sql.toString();
}
